### ISSUE TITLE
ensure 100% branch coverage for R package

### ISSUE THREAD

**Issue by rachelkriggs** [UBC-MDS/exploreR#20]
to be done by Jim

**Comment by jpush1773** [comment]
Will have draft done pm, Feb 28th.

**Comment by rachelkriggs** [comment]
Sorry for the slow response on this Jim, I seemed to have missed this comment. But yes, that was just checking for valid input.

**Comment by jpush1773** [comment]
Resolved issue: Ran coverage_package() on all functions. Initially, 2/3 functions had 100% coverage, but variable_summary() achieved 85%. Modified test to ensure all variables were tested and this resulted in 100% coverage for variable_summary(), too.

**Comment by jpush1773** [comment]
Moved covr_report.png to main directory to make it more visible.  
![image](https://user-images.githubusercontent.com/43223067/53699600-f79e8900-3d9e-11e9-9d76-6dfddc57e0f2.png)
