### ISSUE TITLE
ensure tests run for all R functions

### ISSUE THREAD

**Issue by jpush1773** [UBC-MDS/exploreR#23]

**Comment by jpush1773** [comment]
Ran with devtools::test() - passed, no errors.

ran with devtools::check() and 2 comments returned. Not sure of significance - to discuss.


![image](https://user-images.githubusercontent.com/43223067/53583647-d9ceeb00-3b36-11e9-80e4-28d6c701dc5c.png)

**Comment by rachelkriggs** [comment]
I also ran `devtools::test()` and `devtools::check()` and get full passes on both.
<img width="827" alt="check_passed" src="https://user-images.githubusercontent.com/43154927/53699028-d5097180-3d98-11e9-90c7-748ec93f299e.png">
<img width="530" alt="tests_passed" src="https://user-images.githubusercontent.com/43154927/53699032-db97e900-3d98-11e9-99b5-d27b397262e2.png">
